{{ config(
    materialized='view'
) }}

WITH sales_lead_conformed AS (
    SELECT * FROM {{ ref('sales_lead') }}
),

final AS (
    SELECT 
LEAD_ID AS GDW_LEAD_ID,
LEAD_TYPE,
SOURCE_SYSTEM_CREATED_DATE AS LEAD_CREATED_DATE,
LEAD_LAST_MODIFIED_DATE,
LEAD_LAST_SOURCE_UPDATE_DATE,
LEAD_SOURCE_ID,
ANNUAL_SALES,
ANNUAL_REVENUE,
DUNS_NUMBER,
LAST_ACTIVITY_DATE,
LEAD_SOURCE,
LEAD_SOURCE_NAME,
REGION,
CONVERTED_ACCOUNT_SOURCE_ID,
SALES_PERSON_ID,
CONVERTED_ACCOUNT_ID,
OWNER_SOURCE_ID,
OWNER_ID,
CREATED_BY_SOURCE_ID,
source_system_created_by_id AS CREATED_BY_ID,
LEAD_STATUS,
ISDELETED,
COUNTRY,
ISCONVERTED,
CHANNEL_PARTNER,
CHANNEL_PARTNER_TYPE AS PARTNER_TYPE,
SUB_SEGMENT,
STRATEGIC_SEGMENT,
MAL_DATE,
NEW_MQL_DATE,
SAL_DATE,
CONVERTED_DATE,
Owner_L4_Manager,
LEADER_SEGMENT
FROM sales_lead_conformed
)

SELECT * FROM final
